/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS FILE IS GENERATED BY CONVEX. DO NOT EDIT.
 */
import { getAllFunctionPaths } from "convex/server";

const fullApi = {
  games: {}
};

export const api = {};
export const internal = {};

// Make api proxy for autocomplete
const apiProxy = new Proxy(api, {
  get(target, prop) {
    if (typeof prop === 'string') {
      return new Proxy({}, {
        get(_, fnName) {
          return `${prop}:${fnName}`;
        }
      });
    }
    return target[prop];
  }
});

Object.assign(api, apiProxy);
