/* eslint-disable */
/**
 * Generated `api` utility types.
 *
 * THIS FILE IS GENERATED BY CONVEX. DO NOT EDIT.
 */
import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as games from "../games.js";

declare const fullApi: ApiFromModules<{
  games: typeof games;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
