/* eslint-disable */
/**
 * Generated server utility types.
 *
 * THIS FILE IS GENERATED BY CONVEX. DO NOT EDIT.
 */
import {
  ActionBuilder,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  GenericDatabaseReader,
  GenericDatabaseWriter,
} from "convex/server";
import { DataModel } from "./dataModel.js";

/**
 * Define a query in this Convex app's public API.
 *
 * This function will be allowed to read your Convex database and will be accessible from the client.
 */
export declare const query: QueryBuilder<DataModel, "public">;

/**
 * Define a query that is only accessible from other Convex functions (but not from the client).
 *
 * This function will be allowed to read from your Convex database. It will not be accessible from the client.
 */
export declare const internalQuery: QueryBuilder<DataModel, "internal">;

/**
 * Define a mutation in this Convex app's public API.
 *
 * This function will be allowed to modify your Convex database and will be accessible from the client.
 */
export declare const mutation: MutationBuilder<DataModel, "public">;

/**
 * Define a mutation that is only accessible from other Convex functions (but not from the client).
 *
 * This function will be allowed to modify your Convex database. It will not be accessible from the client.
 */
export declare const internalMutation: MutationBuilder<DataModel, "internal">;

/**
 * Define an action in this Convex app's public API.
 *
 * An action is a function which can execute any JavaScript code, including non-deterministic
 * code and code with side-effects, like calling third-party services.
 * They can be run in Convex's JavaScript environment or in your environment on Node.js.
 */
export declare const action: ActionBuilder<DataModel, "public">;

/**
 * Define an action that is only accessible from other Convex functions (but not from the client).
 */
export declare const internalAction: ActionBuilder<DataModel, "internal">;

/**
 * Define an HTTP action.
 *
 * This function will be used to respond to HTTP requests received by a Convex
 * deployment if the requests matches the path and method that you specify in the
 * HTTP router. See the [docs](https://docs.convex.dev/functions/http-actions) for more.
 */
export declare const httpAction: HttpActionBuilder;

/**
 * A type for a Convex query function that is part of this app's public API.
 */
export type QueryCtx = GenericQueryCtx<DataModel>;

/**
 * A type for a Convex mutation function that is part of this app's public API.
 */
export type MutationCtx = GenericMutationCtx<DataModel>;

/**
 * A type for a Convex action function that is part of this app's public API.
 */
export type ActionCtx = GenericActionCtx<DataModel>;

/**
 * A type for querying your database from a query or mutation function.
 */
export type DatabaseReader = GenericDatabaseReader<DataModel>;

/**
 * A type for writing to your database from a mutation function.
 */
export type DatabaseWriter = GenericDatabaseWriter<DataModel>;
